### ISSUE TITLE
Updated to new upload

### ISSUE THREAD

**Issue by bennerj** [corelight/ecs-logstash-mappings#31]
I am getting the following after updating to the latest upload.

```
 Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:ecs-logstash-corelight, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of [ \\t\\r\\n], \"#\", \"if\", [A-Za-z0-9_-], '\"', \"'\", \"}\" at line 30, column 6 (byte 1208) after filter {\r\n  if [@metadata][z_no_reuse][event_type] == \"corelight\" and [@metadata][z_no_reuse][event_sub_type] == \"ldap\" {\r\n    mutate {\r\n      update => {\r\n        \"[@metadata][temporary_metadata_index_name_suffix]\" => \"various\"\r\n        \"[event][category]\" => \"network\"\r\n      }\r\n      rename => {\r\n        \"message_id\" => \"[ldap][message_id]\"\r\n        \"version\" => \"[ldap][version]\"\r\n        \"opcode\" => \"[ldap][operation]\"\r\n        \"proto\" => \"[network][transport]\"\r\n        \"diagnostic_message\" => \"[ldap][diagnostic_message]\"\r\n        \"object\" => \"[ldap][object]\"\r\n        \"argument\" => \"[ldap][argument]\"\r\n      }\r\n      add_field => {\r\n        \"[network][protocol]\" => \"ldap\"\r\n        \"[@metadata][etl][pipeline]\" => \"filter-mutate-544e6feacec6-main-ldap-20230307.01\"\r\n      }\r\n      tag_on_failure => \"_mutate_error-544e6feacec6\"\r\n      id => \"filter-mutate-544e6feacec6\"\r\n    }", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:32:in `compile_imperative'", "org/logstash/execution/AbstractPipelineExt.java:234:in `initialize'", "org/logstash/execution/AbstractPipelineExt.java:168:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:48:in `initialize'", "org/jruby/RubyClass.java:911:in `new'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:50:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:386:in `block in converge_state'"]}
[2023-03-09T15:12:31,545][INFO ][logstash.runner          ] Logstash shut down.
[2023-03-09T15:12:31,549][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
org.jruby.exceptions.SystemExit: (SystemExit) exit
        at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:790) ~[jruby.jar:?]
        at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:753) ~[jruby.jar:?]
        at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:91) ~[?:?]
```

Any idea's on what is going on? Looking at the error more indepth, looks like 3111-corelight-ecs-ldap-filter.conf is missing the last two }

**Comment by hunter32me** [comment]
Typo fixed
